### ISSUE TITLE
Detect room

### ISSUE THREAD

**Issue by vitrinh282** [cansik/architectural-floor-plan#46]
Your release cannot detect any room.
And I can't impport library  because error target

**Comment by cansik** [comment]
If you really want to get support, please give us a bit more information about what you are trying to do and what does not work.

I just tried the release on the following plan:
![image](https://user-images.githubusercontent.com/5220162/34605216-09d1520a-f20b-11e7-80ed-4972d01e9f44.png)

With a bit of parameter tweaking you get very good results:
![image](https://user-images.githubusercontent.com/5220162/34605347-8c098ff8-f20b-11e7-95de-63deb26727c7.png)

**Comment by vitrinh282** [comment]
I mean i tried your release version , after i execute run64.bat , then import image , just enter Run Workflow -> Next, but there is no room detected, I tried your image here but same, Please help me how to use and export like output you show me

**Comment by vitrinh282** [comment]
![image](https://user-images.githubusercontent.com/28979711/34657598-88c509a8-f3dc-11e7-8080-5a00a83cbba7.png)
![image](https://user-images.githubusercontent.com/28979711/34657602-925e5884-f3dc-11e7-919a-4dc94f3c3f3b.png)
![image](https://user-images.githubusercontent.com/28979711/34657604-9b0443e0-f3dc-11e7-9e00-3aa532ba96d4.png)

**Comment by vitrinh282** [comment]
and onething , how to run prooject, i installed kotlin plugin but cannot find javafx

**Comment by cansik** [comment]
The software is not a one click solution for recognising rooms. It supports you finding the doors, outer walls and rooms. But you as a user have to select the right parameters.

Regarding your screenshot, it seems that you just stopped after the door recognition, which did not find anything because of the wrongly selected parameters. But there are multiple other pipeline steps:

![image](https://user-images.githubusercontent.com/5220162/34667329-e0d7287e-f468-11e7-918b-d4291cb756fc.png)

For development, you need JDK8 and then just run gradle to build. On windows it's:

```bash
gradlew.bat build
```

**Comment by vitrinh282** [comment]
Could you please demo progress  how to find all room ? like video maybe .

**Comment by vitrinh282** [comment]
And i look in your source. I see 2 testImage 
 1 : MorphologicalTransform()
     RectangleRoomDetection() -> this mean thi contour around ? or every room in floor plan. 
 I tried 2 step in code java , it just remvoe some stuff, not show anything room, remove window ....

2: CascadeClassifierDetector(AFImage.DOOR_CASCADE, AFImage.DOOR_ATTRIBUTE_NAME), -> 
                            MorphologicalTransform(),
                            GapClosingAlgorithm(),
                            NikieRoomDetection(),-> other way to detect every room or something
                            ConnectedComponentDetection() -> connect door , room ?
I saw many algorithms, could you details them a little to easy understand , Thks man :)

**Comment by cansik** [comment]
Have you read the [thesis / documentation](https://github.com/cansik/architectural-floor-plan/releases/download/v1.0/AASAFP_BruggisserWyss_2017.pdf) of the project? On page 27 is the workflow 3 described, which is used for the actual process.
And no, I won't explain all of them in detail, because everything is written in the documentation.

Btw. it is not Java, it's Kotlin that we used ;) but it should be possible to call it with Java.

**Comment by vitrinh282** [comment]
hi, could you make video demo for output above ?.

**Comment by vitrinh282** [comment]
could you give me example , negative image and background image in training ?

**Comment by cansik** [comment]
No I can't. I have to work on other projects at the moment and I do not have the time to create tutorial videos or examples. The project was a proof of concept and we shared the code for others to have an example.

**Comment by mohitkarnajawala** [comment]
Hello sir, can we implement the same functionality in android in java or not ? IF yes how . I have download your code but not getting how  actually to run it , i am have jdk 14 and also run the command in command prompt as you mentioned but not works .please help

**Comment by mohitkarnajawala** [comment]
can it be possible to open this demo project to open in android studio?
