### ISSUE TITLE
room count it not works in layers

### ISSUE THREAD

**Issue by anuj-njoshi** [cansik/architectural-floor-plan#47]
i tried this on my machine.first algorithm  which is count door is showing perfectly but  after all algorithms step done the room count showing only one which not expected as floorplan  i used this imges from http://www.conceptdraw.com/solution-park/building-basic-floor-plans

**Comment by cansik** [comment]
If I take following plan as starting point: [![Building-Plans-Basic-Floor-Plans-Mini-Hotel-Floor-Plan.png](http://www.conceptdraw.com/solution-park/resource/images/solutions/building-basic-floor-plans/Building-Plans-Basic-Floor-Plans-Mini-Hotel-Floor-Plan.png)](http://www.conceptdraw.com/solution-park/resource/images/solutions/building-basic-floor-plans/Building-Plans-Basic-Floor-Plans-Mini-Hotel-Floor-Plan.png)

I get following result, with two manual corrections, which are highlighted in red. One correction is because it is a two-wing-door, the other is because of the simple outer wall closing is not working with concave walls. But it looks pretty good, with all 18 rooms detected. The two rooms outside the house are false detections and can be deleted.

![image](https://user-images.githubusercontent.com/5220162/38616215-79b9899c-3d93-11e8-95e6-b4b11d8eb917.png)

Here is the room segmentation map:
![image](https://user-images.githubusercontent.com/5220162/38616027-eb517d36-3d92-11e8-928c-7183c4beb822.png)

Could you give me an example plan, which is not working?
