### ISSUE TITLE
Questions on Code Functionality

### ISSUE THREAD

**Issue by Sahil-Mehta881** [cansik/architectural-floor-plan#53]
Hello! I'm trying to run floor plan analysis, and I have a few questions:

Can we run the code from the command line with default parameters?
Would I need to label each room manually, or is there a way to expedite associating each room with its name?
Does the inputted floor need to contain specific features (color, line thickness, etc)? What does the training data look like, just to provide a basis for how our input data must look?

Thanks!

**Comment by ifelse-codes** [comment]
@cansik can you please help me in using the project

**Comment by cansik** [comment]
@Sahil-Mehta881 

No, it's not implemented to provide command line arguments and run it completely autonomous. But it would be quite simple to implement, because the UI is just displaying the workflow, which could be skipped ([WorkflowEngine.kt#L33](https://github.com/cansik/architectural-floor-plan/blob/master/afpars/src/main/kotlin/ch/fhnw/afpars/workflow/WorkflowEngine.kt#L33)).

Lableing of the rooms is not implemented, but you could run a text recognition (for example [TextBoxes](https://docs.opencv.org/master/d1/d66/classcv_1_1text_1_1TextDetectorCNN.html)) and assign it to the closest detected room.

Well we tried a lot of different floor plans (also just some from the internet). Because we are heavily relying on thresholding for the wall detection, it is necessary that the walls are thick enough.
